### ISSUE TITLE
LiveTranscription

### ISSUE THREAD

**Issue by SishaarRao** [deepgram/deepgram-python-sdk#127]
## What is the current behavior?
I keep seeing the following error emitted by my server

```
Task exception was never retrieved
future: <Task finished name='Task-192191' coro=<LiveTranscription._start() done, defined at /Users/sishaar/.pyenv/versions/3.11.4/lib/python3.11/site-packages/deepgram/transcription.py:178> exception=ConnectionClosedOK(Close(code=1000, reason=''), Close(code=1000, reason=''), True)>
Traceback (most recent call last):
  File "/Users/sishaar/.pyenv/versions/3.11.4/lib/python3.11/site-packages/deepgram/transcription.py", line 222, in _start
    await self._socket.send(body)
  File "/Users/sishaar/.pyenv/versions/3.11.4/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/Users/sishaar/.pyenv/versions/3.11.4/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
```
Here is the file I use to manage my Deepgram connections - am I not registering/handling errors correctly?
```python
class _DeepgramConnectionPool:
  def __init__(self):
    self.connections: LiveTranscription = []
    self.deepgram_hosted = Deepgram('<elided>')
    self.deepgram_onprem = Deepgram({'api_key': '', 'api_url': '<elided>'})

  async def get_connection(self, config: dict = {}):
    # default to use hosted deepgram
    self.deepgram = self.deepgram_hosted
    if config.get("enable_to_use_deepgram_on_premise") == "true":
      self.deepgram = self.deepgram_onprem
    try:
      deepgram_config = config.get('country_code_configs', {})
      model = deepgram_config.get("model", '<elided>')
      tier = 'enhanced' if model == 'nooks' else deepgram_config.get("tier", 'base')
      version = 'v1' if model == 'nooks' else deepgram_config.get('version', 'latest')

      async def _get_connection():
        return await self.deepgram.transcription.live(
          encoding='mulaw',
          model=model,
          tier=tier,
          version=version,
          sample_rate=8000,
          punctuate=True,
          interim_results=True,
          language='en-US',
          times=False,
        )

      connection: LiveTranscription = await Retry(_get_connection, delay_s=0.1, factor=1.2)
      connection.register_handler(LiveTranscriptionEvent.ERROR, lambda error: logger.error('Error during connection', exception=error))
      return connection
    except ConnectionClosedOK:
      logger.log('Deepgram websocket connection closed')
    except Exception as e:
      logger.error('Error creating connection: ', exception=e)
      raise e

DeepgramConnectionPool = _DeepgramConnectionPool()
```

Later on, I close the connection with the following piece of code
```python
    async def close_deepgram(self):
        self.logger.debug("Closing Deepgram Connection")
        if self.deepgram:
            await self.deepgram.finish()
            self.logger.log('Closed Deepgram Connection')
```            

## Please tell us about your environment

> We want to make sure the problem isn't specific to your operating system or programming language.
  
- **Operating System/Version: MacOS
- **Language: Python

**Comment by DamienDeepgram** [comment]
Are you using the keepalive message when your not sending any audio we will close the stream unless you send us a keepalive message

https://developers.deepgram.com/reference/streaming#stream-keepalive

**Comment by dvonthenen** [comment]
The live client is getting reworked. Please check back when PR is merged.

**Comment by dvonthenen** [comment]
A new release was just posted which should address this problem, please take a look:
https://github.com/deepgram/deepgram-python-sdk/releases/tag/v3.0.0-alpha.1

**Comment by dvonthenen** [comment]
Hi @SishaarRao have you been able to try the latest v3 release?

**Comment by dvonthenen** [comment]
Closing due to inactivity. If there is still a problem with the latest [release](https://github.com/deepgram/deepgram-python-sdk/releases/tag/v3.0.0-beta.1), please reopen or file a new issue. thanks!
