### ISSUE TITLE
DeepgramApiError with None message

### ISSUE THREAD

**Issue by jonahweissman** [deepgram/deepgram-python-sdk#240]
## What is the current behavior?

When I get a 400 error from the API, the error raised by the SDK contains no context or error message, other than the status code.

## Steps to reproduce

Here's a unit test. I got the error payload from the 400 example on this page: https://developers.deepgram.com/reference/listen-file
```
import json
import unittest
from unittest.mock import patch, Mock

from deepgram import DeepgramClient, PrerecordedOptions
from deepgram.clients.errors import DeepgramApiError
from httpx import HTTPStatusError

class TestDeepgramTranscriber(unittest.IsolatedAsyncioTestCase):
    @patch('httpx.Client.request', new_callable=Mock)
    async def test_transcribe_url_no_retry_example(self, mock_post):
        api_key = 'your_api_key'
        deepgram_client = DeepgramClient(api_key)

        mock_response = Mock()
        mock_response.status_code = 400
        mock_response.text = json.dumps(
            {
                "err_code": "Bad Request",
                "err_msg": "Content-type was application/json, but we could not process the JSON payload.",
                "request_id": "4399e2a5-2b29-4e1e-9456-79043cc88d0a"
            }
        )

        mock_response.raise_for_status = Mock(side_effect=HTTPStatusError("message", request={}, response=mock_response))

        mock_post.return_value = mock_response

        audio_url = 'https://example.com/audio.mp3'
        source = {'url': audio_url}
        options = PrerecordedOptions(
            punctuate=False,
            model="nhtsa",
            version="v1_dc",
        )
        with self.assertRaises(DeepgramApiError) as context:
            await deepgram_client.listen.asyncprerecorded.v("1").transcribe_url(source, options)

        # Assert that the request was not retried and the result is as expected
        mock_post.assert_called_with(
            'POST',
            'https://api.deepgram.com/v1/listen?model=nhtsa&punctuate=false&version=v1_dc',
            headers={'Accept': 'application/json', 'Authorization': 'Token your_api_key'},
            json={'url': 'https://example.com/audio.mp3'}
        )

        self.assertEqual(context.exception.message, 'Content-type was application/json, but we could not process the JSON payload.')
```
## Expected behavior

I'd like the see the error message that the API returns, and the request ID, in case I need to reach out to support.

## Please tell us about your environment
  
- **Operating System/Version:** Linux
- **Language:** Python

## Other information

I think the error message key should actually be `err_msg` instead of `message` on this line
https://github.com/deepgram/deepgram-python-sdk/blob/5a29caedd097bdffe7e8d03536ff119ffd29bfca/deepgram/clients/abstract_sync_client.py#L113

Here's a full stacktrace that I got in my production environment:
```
[ERROR] DeepgramApiError: DeepgramApiError: None (Status: 400)
Traceback (most recent call last):
  File "/var/task/app.py", line 330, in lambda_handler
    asyncio.run(transcribe_pipeline())
  File "/var/lang/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/var/lang/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/var/lang/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
  File "/var/task/app.py", line 282, in transcribe_pipeline
    transcript = await deepgram_client.transcribe_url(audio_url)
  File "/var/task/datadrivenstreets/retry.py", line 23, in wrapper
    raise e
  File "/var/task/datadrivenstreets/retry.py", line 19, in wrapper
    result = await func(*args, **kwargs)
  File "/var/task/datadrivenstreets/clients/deepgram.py", line 24, in transcribe_url
    .transcribe_url(source, options, timeout=Timeout(10.0, read=20.0))
  File "/var/lang/lib/python3.11/site-packages/deepgram/clients/prerecorded/v1/client.py", line 77, in transcribe_url
    result = self.post(
  File "/var/lang/lib/python3.11/site-packages/deepgram/clients/abstract_sync_client.py", line 49, in post
    return self._handle_request(
  File "/var/lang/lib/python3.11/site-packages/deepgram/clients/abstract_sync_client.py", line 112, in _handle_request
    raise DeepgramApiError(
```

**Comment by dvonthenen** [comment]
This PR should be merged.

BTW @jonahweissman if you at all want to contribute those unit tests, that would be awesome!

**Comment by dvonthenen** [comment]
should be available in https://github.com/deepgram/deepgram-python-sdk/releases/tag/v3.0.2
