### ISSUE TITLE
Speech to text realtime streaming websocket issue in new version 3.1.1

### ISSUE THREAD

**Issue by cyzanfar** [deepgram/deepgram-python-sdk#279]
## What's happening that seems wrong?

Hey! I'm a Deepgram customer; love your product.

Recently I upgraded the deepgram python sdk from 3.0.0 to 3.1.1. However I'm now experiencing an error when deepgram is attempting to connect via websocket.

*deepgram/client/live/v1/async_client.py*
```
async def _socket_connect(websocket_url, headers):
    destination = websocket_url
    updated_headers = headers
    return await websockets.connect(
        destination, extra_headers=updated_headers, ping_interval=5
    )
```

**error**

INFO:     Started server process [73764]
INFO:     Waiting for application startup.
Starting up...
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
Incoming call received.
INFO:     ::1:50420 - "POST /incoming HTTP/1.1" 200 OK
INFO:     ('::1', 50425) - "WebSocket /connection" [accepted]
INFO:     connection open
START EVENT RECEIVED
version: 1
version: 1
path: deepgram.clients.live.v1.async_client
path: deepgram.clients.live.v1.async_client
className: AsyncLiveClient
className: AsyncLiveClient
Version.v succeeded
Version.v succeeded
addons: None
options: {}
LiveOptions switching class -> json
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/cyzanfar/Desktop/llm/voicellm/venv/lib/python3.11/site-packages/deepgram/clients/live/v1/async_client.py", line 73, in start
    self._socket = await _socket_connect(url_with_params, self.config.headers)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cyzanfar/Desktop/llm/voicellm/venv/lib/python3.11/site-packages/websockets/legacy/client.py", line 325, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 400

## Here's my implementation:
```
import pdb
import os
import dotenv
import asyncio
from time import perf_counter
from deepgram import (
    LiveTranscriptionEvents,
    LiveOptions,
    DeepgramClient,
    DeepgramClientOptions,

)


dotenv.load_dotenv()
DEEPGRAM_API_KEY = os.environ.get("DEEPGRAM_API_KEY")


class TranscriptionService:
    def __init__(self, on_transcript_callback, on_interrupt_callback, audio_playing_callback, is_beginning_of_call):
        self.deepgram_client = DeepgramClient(config=DeepgramClientOptions(verbose=20))
        # self.deepgram_client = AsyncLiveClient(DeepgramClientOptions(api_key=DEEPGRAM_API_KEY, verbose=10))
        self.dg_connection = None
        self.is_beginning_of_call = is_beginning_of_call
        self.on_transcript_callback = on_transcript_callback
        self.on_interrupt_callback = on_interrupt_callback
        self.audio_playing_callback = audio_playing_callback
        self.transcription_begins = False
        self.sentence = ''
        # self.dg_connection = self.deepgram_client.listen.live.v("1")

    async def start_transcription(self):
        self.dg_connection = self.deepgram_client.listen.live.v("1")

        def on_message(self, result, **kwargs):
            print(self, result, kwargs)
            if result is None:
                return
            transcribed_complete_time = perf_counter()
            print(f"""
            Alt Length: {len(result.channel.alternatives)}
            sentence: '{result.channel.alternatives[0].transcript}'
            speech_final: {result.speech_final}
            is_final: {result.is_final}
            """)
            print("------------------------------------------")
            self.sentence += result.channel.alternatives[0].transcript
            if result.speech_final:
                self.transcription_begins = True
                # Access the confidence of the whole sentence in the first alternative
                # print(result.channel.alternatives)
                # alternative = result.channel.alternatives[0]
                #
                # # if alternative.confidence > 0.9:
                #
                # sentence = alternative.transcript
                if self.sentence:
                    print(f"TRANSCRIPT {self.sentence}")
                    # is_audio_playing = self.audio_playing_callback()
                    # if not self.is_beginning_of_call and is_audio_playing:
                    #     asyncio.create_task(self.on_interrupt_callback())
                    # self.is_beginning_of_call = False
                    asyncio.create_task(self.on_transcript_callback(self.sentence, transcribed_complete_time))
                    self.sentence = ''
                # else:
                #     print(f"Low-confidence transcript: {alternative.transcript}")

        def on_utterance_end(self, utterance_end, **kwargs):
            print(f"[UTTERNANCE_END]: \n\n{utterance_end}\n\n")

        def on_metadata(self, metadata, **kwargs):
            if metadata is None:
                return
            print(f"\n\nMetadata: {metadata}\n\n")

        def on_error(self, error, **kwargs):
            if error is None:
                return
            print(f"\n\nError: {error}\n\n")

        self.dg_connection.on(LiveTranscriptionEvents.Transcript, on_message)
        self.dg_connection.on(LiveTranscriptionEvents.Metadata, on_metadata)
        self.dg_connection.on(LiveTranscriptionEvents.Error, on_error)
        self.dg_connection.on(LiveTranscriptionEvents.UtteranceEnd, on_utterance_end)

        options = LiveOptions(
            model="nova-2",
            interim_results=True,
            language="en-US",
            encoding="mulaw",
            sample_rate="8000",
            punctuate=True,
            endpointing=400,
            utterance_end_ms=200
        )

        await self.dg_connection.start(options)

    async def send_audio_data(self, data):
        if not self.dg_connection:
            print("Deepgram live transcription object is 'None'; cannot send data.")
            return  # Early exit if the transcription isn't started
        await self.dg_connection.send(data)

    async def stop_transcription(self):
        if self.dg_connection:
            await self.dg_connection.finish()
            self.dg_connection = None
```

**Comment by cyzanfar** [comment]
***UPDATE***

I found the issue regarding the error above; the `utterance_end_ms` parameter value cannot be <1000.
The documentation mentions that it's not recommended:

[documentation](https://developers.deepgram.com/docs/understanding-end-of-speech-detection#using-utteranceend)
> In practice, you should set the value of utterance_end_ms to be 1000 ms or higher. Deepgram's Interim Results are typically sent every 1 second, so using a value of less than 1 second will not offer any benefits.


however, having a utternance_end_ms value <1000 yields a 400 bad request and I think Deepgram's error handling could be more informative.

I had to do some digging to to get the raw response:
```
HTTP/1.1 400 Bad Request'
status_code 400 reason Bad Request headers content-type: application/json
dg-error: Invalid 'utterance_end_ms' value of '999'.
content-length: 145
access-control-allow-credentials: true
vary: origin
vary: access-control-request-method
vary: access-control-request-headers
dg-request-id: 587b3227-f6ca-4818-bb4d-028182adf4ea
date: Wed, 31 Jan 2024 07:25:49 GMT
```

After adjusting the utterance_end_ms to 1000 and changing `self.dg_connection = self.deepgram_client.listen.live.v("1")` to `self.dg_connection = self.deepgram_client.listen.asynclive.v("1")` then i'm getting this error:

```
deepgram/clients/live/v1/async_client.py:219: RuntimeWarning: coroutine 'AsyncLiveClient._emit' was never awaited
  self._emit(LiveTranscriptionEvents.Error, error)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task exception was never retrieved
future: <Task finished name='Task-16' coro=<AsyncLiveClient._start() done, defined at deepgram/clients/live/v1/async_client.py:97> exception=TypeError("Logger._log() got an unexpected keyword argument 'error'")>
Traceback (most recent call last):
  File "deepgram/clients/live/v1/async_client.py", line 114, in _start
    await self._emit(
  File "deepgram/clients/live/v1/async_client.py", line 95, in _emit
    await handler(self, *args, **kwargs)
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by dvonthenen** [comment]
I can forward this onto the API team to come up with a better error message. I believe this is documented though:
https://developers.deepgram.com/docs/understanding-end-of-speech-detection

The wording on the documentation is a little confusing. Suggesting that you might be able to have the value be less than 1000. Will fix that.
```
In practice, you should set the value of utterance_end_ms to be 1000 ms or higher. Deepgram's Interim Results are typically sent every 1 second, so using a value of less than 1 second will not offer any benefits.
```

**Comment by cyzanfar** [comment]
Thanks for the quick reply @dvonthenen 

Would you mind helping me out with the latter issue:


After adjusting the utterance_end_ms to 1000 and changing self.dg_connection = self.deepgram_client.asynclive.live.v("1") to self.dg_connection = self.deepgram_client.listen.asynclive.v("1") then i'm getting this error:

```
deepgram/clients/live/v1/async_client.py:219: RuntimeWarning: coroutine 'AsyncLiveClient._emit' was never awaited
  self._emit(LiveTranscriptionEvents.Error, error)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Task exception was never retrieved
future: <Task finished name='Task-16' coro=<AsyncLiveClient._start() done, defined at deepgram/clients/live/v1/async_client.py:97> exception=TypeError("Logger._log() got an unexpected keyword argument 'error'")>
Traceback (most recent call last):
  File "deepgram/clients/live/v1/async_client.py", line 114, in _start
    await self._emit(
  File "deepgram/clients/live/v1/async_client.py", line 95, in _emit
    await handler(self, *args, **kwargs)
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by dvonthenen** [comment]
This was solved in Discord:
https://discord.com/channels/1108042150941294664/1202113397270003763

**Comment by cyzanfar** [comment]
For context, the event handler function defined need to be `async`

```
async def on_message()
```

instead of

```
def on_message
```

**Comment by rutvik106** [comment]
What could be the max value for utterance_end_ms?

**Comment by swimleftproducts** [comment]
The discord link seems to be unreachable?
