### ISSUE TITLE
`dg.listen.prerecorded.v("1").transcribe_url` fails on long audio with `httpx.HTTPStatusError: Client error '411 Length Required' for url`

### ISSUE THREAD

**Issue by richieM** [deepgram/deepgram-python-sdk#293]
I'm attempting to call `dg.listen.prerecorded.v("1").transcribe_url(source, options)` and the call is failing on longer audio (45+ min) with `httpx.HTTPStatusError: Client error '411 Length Required' `

Here's my setup:
```
options = PrerecordedOptions(
                punctuate=True,
                model='2-ea',
                tier='nova',
                #"tier": 'nova-2-ea',
                diarize=True,
                smart_format=True,
            )

from deepgram import (
    DeepgramClient,
    PrerecordedOptions,
)

dg_key = os.environ.get('DEEPGRAM_KEY')
dg = DeepgramClient(dg_key)
```

Here's the full stack of 2 failures on longer audio (47 mins and 56 mins, respectively) followed by a success on a deepgram hosted short mp3.
```
### FAILURE #1
>>> source = {'url': 'http://openmedia.yale.edu/cgi-bin/open_yale/media_downloader.cgi?file=/courses/spring07/psyc110/mp3/psyc110_06_020507.mp3'}
>>> currResponse = dg.listen.prerecorded.v("1").transcribe_url(source, options)WARNING: Tier is deprecated. Will be removed in a future version.
WARNING: Tier is deprecated. Will be removed in a future version.
WARNING: Tier is deprecated. Will be removed in a future version.              
WARNING: Tier is deprecated. Will be removed in a future version.
WARNING: Tier is deprecated. Will be removed in a future version.
WARNING: Tier is deprecated. Will be removed in a future version.
WARNING: Tier is deprecated. Will be removed in a future version.
WARNING: Tier is deprecated. Will be removed in a future version.
Traceback (most recent call last):                                             
  File "/home/richie/nlp/.venv/lib/python3.10/site-packages/deepgram/clients/abstract_sync_client.py", line 104, in _handle_request
    response.raise_for_status()                                                
  File "/home/richie/nlp/.venv/lib/python3.10/site-packages/httpx/_models.py", line 759, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '411 Length Required' for url 'https://api.deepgram.com/v1/listen?diarize=true&model=2-ea&punctuate=true&smart_format=true&tier=nova'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/411

The above exception was the direct cause of the following exception:                     

Traceback (most recent call last):          
  File "<stdin>", line 1, in <module>       
  File "/home/richie/nlp/.venv/lib/python3.10/site-packages/deepgram/clients/prerecorded/v1/client.py", line 83, in transcribe_url
    result = self.post(                     
  File "/home/richie/nlp/.venv/lib/python3.10/site-packages/deepgram/clients/abstract_sync_client.py", line 48, in post
    return self._handle_request(            
  File "/home/richie/nlp/.venv/lib/python3.10/site-packages/deepgram/clients/abstract_sync_client.py", line 111, in _handle_request
    raise DeepgramApiError(                 
deepgram.clients.errors.DeepgramApiError: DeepgramApiError: Fetching failed to get valid content-length. (Status: 411)


### FAILURE #2
>>> source = {'url': 'http://openmedia.yale.edu/cgi-bin/open_yale/media_downloader.cgi?file=/courses/spring07/astr160/mp3/astr160_15_030807.mp3'}
>>> currResponse = dg.listen.prerecorded.v("1").transcribe_url(source, options)          
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
Traceback (most recent call last):          
  File "/home/richie/nlp/.venv/lib/python3.10/site-packages/deepgram/clients/abstract_sync_client.py", line 104, in _handle_request
    response.raise_for_status()             
  File "/home/richie/nlp/.venv/lib/python3.10/site-packages/httpx/_models.py", line 759, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)                       
httpx.HTTPStatusError: Client error '411 Length Required' for url 'https://api.deepgram.com/v1/listen?diarize=true&model=2-ea&punctuate=true&smart_format=true&tier=nova'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/411

The above exception was the direct cause of the following exception:                     

Traceback (most recent call last):          
  File "<stdin>", line 1, in <module>       
  File "/home/richie/nlp/.venv/lib/python3.10/site-packages/deepgram/clients/prerecorded/v1/client.py", line 83, in transcribe_url
    result = self.post(                     
  File "/home/richie/nlp/.venv/lib/python3.10/site-packages/deepgram/clients/abstract_sync_client.py", line 48, in post
    return self._handle_request(            
  File "/home/richie/nlp/.venv/lib/python3.10/site-packages/deepgram/clients/abstract_sync_client.py", line 111, in _handle_request
    raise DeepgramApiError(                 
deepgram.clients.errors.DeepgramApiError: DeepgramApiError: Fetching failed to get valid content-length. (Status: 411)

### SUCCESS ON SHORT AUDIO
>>> source = {'url': 'https://dpgr.am/spacewalk.wav'}                                    
>>> currResponse = dg.listen.prerecorded.v("1").transcribe_url(source, options)WARNING: Tier is deprecated. Will be removed in a future version.
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
WARNING: Tier is deprecated. Will be removed in a future version.                        
```                                         

What am I doing wrong here?

## Please tell us about your environment
deepgram-sdk==3.1.3
 
Thanks!

**Comment by dvonthenen** [comment]
It seems like you aren't passing the correct input to the function. Take a look at the example here:
https://github.com/deepgram/deepgram-python-sdk/blob/main/examples/prerecorded/url/main.py

**Comment by richieM** [comment]
You are in fact correct, it seems the issue was the mp3 URL I was passing. It's working now on another mp3 url `https://audio.hbr.org/on-strategy/20230815120249-19_3WaystoBuildCritical-ThinkingSkills.mp3`. Thanks for bearing with me @dvonthenen
