### ISSUE TITLE
N best fails for batch transcription 

### ISSUE THREAD

**Issue by AndreMilota** [deepgram/deepgram-python-sdk#88]
## What is the current behavior?

I need to get N best as many as possible, time stamps and scores but when I ask for more then 2 N best it fails it is intermittent even with the same audio file and a request for the same number of n best. 

I am using  Windows 10 64 bit 21H2 19044.2965 Windows Feature Experience Pack 1000.19041.1000.0

this is a little python file and I am using a wave file I recorded that lasts just a few seconds 

> What's happening that seems wrong?

I get a bunch of error messages and it crashes 

Traceback (most recent call last):
  File "C:\Users\Andre\source\repos\Quintessence\Python\Deepgram_Batch\Lib\Main.py", line 47, in <module>
    main()
  File "C:\Users\Andre\source\repos\Quintessence\Python\Deepgram_Batch\Lib\Main.py", line 42, in main
    response = deepgram.transcription.sync_prerecorded(source, {'punctuate': True, 'alternatives': 5})
  File "C:\Users\Andre\source\repos\Quintessence\Python\Deepgram_Batch\lib\site-packages\deepgram\transcription.py", line 355, in sync_prerecorded
    return SyncPrerecordedTranscription(
  File "C:\Users\Andre\source\repos\Quintessence\Python\Deepgram_Batch\lib\site-packages\deepgram\transcription.py", line 111, in __call__
    return _sync_request(
  File "C:\Users\Andre\source\repos\Quintessence\Python\Deepgram_Batch\lib\site-packages\deepgram\_utils.py", line 156, in _sync_request
    raise exc # stream is now invalid as payload
  File "C:\Users\Andre\source\repos\Quintessence\Python\Deepgram_Batch\lib\site-packages\deepgram\_utils.py", line 153, in _sync_request
    return attempt()
  File "C:\Users\Andre\source\repos\Quintessence\Python\Deepgram_Batch\lib\site-packages\deepgram\_utils.py", line 148, in attempt
    raise (Exception(f'DG: {exc}') if exc.status < 500 else exc)
  File "C:\Users\Andre\source\repos\Quintessence\Python\Deepgram_Batch\lib\site-packages\deepgram\_utils.py", line 139, in attempt
    with urllib.request.urlopen(req) as resp:
  File "C:\Users\Andre\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Andre\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\Andre\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\Andre\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\Andre\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\Andre\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

Process finished with exit code 1

## Steps to reproduce

run this program after you add code to set:

DEEPGRAM_API_KEY = 

PATH_TO_FILE =

from deepgram import Deepgram
import json
import os

def main():
    # Initializes the Deepgram SDK
    deepgram = Deepgram(DEEPGRAM_API_KEY)
    # Open the audio file
    with open(PATH_TO_FILE, 'rb') as audio:
        # ...or replace mimetype as appropriate
        source = {'buffer': audio, 'mimetype': 'audio/wav'}
        response = deepgram.transcription.sync_prerecorded(source, {'punctuate': True, 'alternatives': 5})
        print(json.dumps(response, indent=4))
        
     
main()

if you reduce 'alternatives': 5 to 2 it will work 
if you reduce it to 3 or 4 it may run some times but not other times

**Comment by jpvajda** [comment]
👋  This is probably better posted in our [Community Forum](https://github.com/orgs/deepgram/discussions) as it doesn't sound like an issue with the SDK. if it's still an issue for you feel free to post there and a Community member can assist.
